# Generated by Django 4.0 on 2022-07-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_register_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
    ]
