# Generated by Django 4.0 on 2022-07-15 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e0068e6-72ab-4fbe-9106-3a89cc8c65b3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66c88ed6-f810-4f0e-a49b-dd2d4971135b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
