# Generated by Django 4.0 on 2022-07-15 22:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_register_bio'),
        ('chats', '0002_alter_message_id_alter_message_sender_alter_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e946924b-fa29-4460-9ecb-08a17814df92'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.register'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.UUIDField(default=uuid.UUID('205c7f7d-9393-42ff-ab55-9fc8ed51f285'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
