# Generated by Django 4.0 on 2022-07-15 23:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_register_bio'),
        ('chats', '0004_alter_message_id_alter_message_receiver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('052014aa-8319-409f-a9d0-fc5a296eb57c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.register'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f69613c7-bff1-4ac8-81fe-8b84e15bb03f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
